### ISSUE TITLE
Missing file config.yaml or typo

### ISSUE THREAD

**Issue by alexander-mazur** [pip-services/pip-services-runtime-node#25]
There is a missing file in solution: config.yaml. 
PipServices.Dummy.Runner.Program points to this file:
`runner.RunWithDefaultConfigFile(args, "..\\..\\..\\..\\config\\config.yaml");`
Or it's just a typo and it should point to "config.example.yaml"

**Comment by alexander-mazur** [comment]
Ops, this issue is related to .NET part: https://github.com/pip-services/pip-services-runtime-dotnet

**Comment by seroukhov** [comment]
We do not checkin config.yaml, since every developer may have own configuration. Instead, you shall copy config.examples.yaml over to config.yaml and make your changes. Developer guide shall mention that step

**Comment by seroukhov** [comment]
The developer guide was updated
